### ISSUE TITLE
ESP32-3248S035 Webinstall and PlatformIO failing

### ISSUE THREAD

**Issue by ohyeah8000** [suchmememanyskill/CYD-Klipper#109]
I`d like to try and use your cool project but unfortunately after webinstall the display stayed completely black. Success notification didn't occur as well.

Then I tried PlatformIO and followed your instructions. 
I did different things. The best result was a flickering display between white screen and colored noise. I used the SD version for the upload which succeeded.... I

Serial connection established. Upload is a success according to platformio. However monitoring fails.

I wonder if my display might be resistive? I don't hve a "C" in the name.

Help to get it run much appreciated!

![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/121863196/838cfe3b-e74c-4ca3-a86e-fdd922c74a8b)

![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/121863196/ef668bea-2138-4119-b3c3-547d2e3df95d)

![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/121863196/329edcd7-71d3-4701-b955-75817b5bd3d8)

![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/121863196/9c012b44-92b5-48d8-b7df-70147a0b8661)

**Comment by suchmememanyskill** [comment]
This looks to be the resistive version. Only the capacitive version of the 3.5" is supported.

Note in platformio you're uploading the smartdisplay version, which has numerous issues (ends with -SD)

**Comment by ohyeah8000** [comment]
Shit. Ok probably that's the reason then....

You have an advice for me where and what I should look for to make this display run as a generic klipperscreen terminal?

**Comment by suchmememanyskill** [comment]
I do not. I don't think such a universal project exists. You may have to build your own vnc viewer.

You could also try to port cyd klipper to this display (easiest probably is to use smartdisplay but iirc it's really slow). The touch calibration on smartdisplay is also very unfinished as nothing uses it right now.
