### ISSUE TITLE
newest build. extrude/retract buttons dont work

### ISSUE THREAD

**Issue by KennyVB** [suchmememanyskill/CYD-Klipper#132]
![image](https://github.com/user-attachments/assets/6425cd49-6d50-4f99-92a9-0ba07aee1170)
pushing on screen buttons results in this in console. klipper v0.12.0-339-g31fe50ffa

**Comment by suchmememanyskill** [comment]
You seem to have enabled the option to use custom gcode for extrusion/retraction, while you have no macros defined for it

**Comment by KennyVB** [comment]
> You seem to have enabled the option to use custom gcode for extrusion/retraction, while you have no macros defined for it

sadly, i havent done anything. just installed, and followed the guide to set it up= network, and then printer ip.
where is the option for disable/enable custom code?

**Comment by suchmememanyskill** [comment]
The default option of 'Custom Filament Move Macros' is off. I don't know what else to say.
"Calls FILAMENT_RETRACT and FILAMENT_EXTRUDE in temperature menu when enabled".

Disable it, and it should use direct gcode commands for it again. You can set these items in settings (macros > settings > 'Custom Filament Move Macros')

**Comment by suchmememanyskill** [comment]
Gonna asssume this is solved
