### ISSUE TITLE
not able to select moonraker port

### ISSUE THREAD

**Issue by CMDR-Wiebster** [suchmememanyskill/CYD-Klipper#15]
i have 2 printers conected to my pi and canot select which printer i want to conect to (automaticly conects to 7125) can i have an option to conect to the other one (7126)

**Comment by suchmememanyskill** [comment]
I don't understand your issue. Do you mean you have 2 moonraker instances running on different ports? And you're asking how to change the port?

**Comment by CMDR-Wiebster** [comment]
yes but i have fixed it (i used the wrong port) my bad
