### ISSUE TITLE
ESP32-3248S035C Board

### ISSUE THREAD

**Issue by jaymcd** [suchmememanyskill/CYD-Klipper#18]
Any chance any has this setup on a board like this one : "DIYmalls 3.5" inch ESP32 Display ESP-WROOM-32 Capacitive Touch Screen TFT LCD Module 320x480 ST7796 ESP32-3248S035_C Development Board for Arduino IDE" I would love to get CYD-Klipper on it but I may have bricked it trying the webbased install.

**Comment by suchmememanyskill** [comment]
Duplicate of #7
