### ISSUE TITLE
Full Keyboard on Wifi Configuration

### ISSUE THREAD

**Issue by willsside** [suchmememanyskill/CYD-Klipper#19]
Thanks for the great project! 

My wifi password has an "&" in the password. Would there be any way to add that symbol to the onscreen keyboard?

**Comment by themacboy** [comment]
hahaha I have the same problem ! hahaha

**Comment by suchmememanyskill** [comment]
Heh, the default lvgl keyboard i'm using doesn't include &, should be fixed bt upgrading the library

**Comment by suchmememanyskill** [comment]
@themacboy @willsside could you try https://github.com/suchmememanyskill/CYD-Klipper/actions/runs/7670721311 ? You can install it by running the commandline tool esptool: `esptool write_flash 0x0 merged-firmware.bin`

**Comment by willsside** [comment]
Just installed the updated firmware as you stated with esptool; new keyboard works great! Thanks for the quick turnaround!

**Comment by themacboy** [comment]
Installed and working perfectlly !

**Comment by razereqqq** [comment]
@suchmememanyskill I've got the same problem, except mine has an "^" in it, and even the updated firmware doesn't include that. I would greatly appreciate it If you could update it once again, changing that wifi password would be a major pain :/

**Comment by suchmememanyskill** [comment]
@razereqqq fix available here: https://github.com/suchmememanyskill/CYD-Klipper/actions/runs/7745111186
