### ISSUE TITLE
A coffee?

### ISSUE THREAD

**Issue by themacboy** [suchmememanyskill/CYD-Klipper#24]
Excuse me, where can I invite you for a coffee?

;)

**Comment by suchmememanyskill** [comment]
I would prefer not to go to unknown places with strangers on the internet to consume a beverage i do not enjoy

**Comment by themacboy** [comment]
LoL!  You misunderstood me hahaha

  I mean if you have some contribution link like use:

https://www.buymeacoffee.com/

**Comment by suchmememanyskill** [comment]
@themacboy i do, it's also listed in the readme but https://ko-fi.com/suchmememanyskill
