### ISSUE TITLE
Theme name does not match colors when not using invert colors

### ISSUE THREAD

**Issue by MartijnGevaert** [suchmememanyskill/CYD-Klipper#31]
Hey,
I noticed that when not using invert colors, the "Theme" names match the theme color, such as Red, Yellow, Orange....
However, when invert colors is not enabled, the values don't match, except for grey, this is the behavior I found:

- Blue = Yellow
- Green = light blue
- Grey = Grey
- Yellow = Blue
- Orange = slightly different blue
- Red = same as above but slightly lighter blue
- Purple = light green

**Comment by suchmememanyskill** [comment]
I don't know what you expected when you invert the colors :/

The feature is there as some CYD models have inverted colors on the screen (the ones with the usb-c port i think). This toggle compensates for that. I don't expect users to use the feature if they don't need it.

**Comment by MartijnGevaert** [comment]
The colors are incorrect when the "Invert Colors" option is NOT enabled.

I do have the version with USB-C, so this then seems to make sense.
