### ISSUE TITLE
Version 1.1.4 is still shown as Version on the Settings Screen in 1.2.0

### ISSUE THREAD

**Issue by N3m3515** [suchmememanyskill/CYD-Klipper#36]
As described in the title

**Comment by suchmememanyskill** [comment]
@N3m3515 yeah uh, this is a bug with the CI. Currently trying to fix it...

**Comment by N3m3515** [comment]
i tried 1.2.1 and it now shows 1.2.0

**Comment by suchmememanyskill** [comment]
Yeah the CI failed. The release notes on the site is decoupled from the actual deployment. But v1.2.0 and v1.2.1 are identical

**Comment by suchmememanyskill** [comment]
All should be right again in the world
