### ISSUE TITLE
Display Layers stay at 0 / 0 during print.  BUG?

### ISSUE THREAD

**Issue by m00x-pixel** [suchmememanyskill/CYD-Klipper#40]
Hi,

Thank you for you great work, i have updated to to the latest version 1.3.0 it was easy as always. 
Maybe there is some Bug.

At second screen during a print the layer info stay always at 0 / 0

![CYD_ESP32_photo_](https://github.com/suchmememanyskill/CYD-Klipper/assets/68993441/b388a92f-01e1-406a-ab07-96298787042e)

But i cannot tell, if it was working with an older version.

Within Fluuid and Mainsail it show the layers like  "Layer 24 / 128" and counting.
Is there anything i need to set or is it not  read the information correctly from moonraker? 

Greetings

**Comment by suchmememanyskill** [comment]
https://moonraker.readthedocs.io/en/latest/printer_objects/#print_stats (see 'info')

https://docs.mainsail.xyz/overview/slicer/prusaslicer#layer-count

If those commands aren't ran (and thus no accurate layer info is available), Mainsail/Fluidd guess the layer count based on the layer height, but this isn't fully accurate (you'll see this if the z compensation is high enough the current layer count becomes unstable).

Cyd-klipper doesn't do this guesswork, and just uses the accurate layer info if available. If there's no info available, it stays at 0.

**Comment by m00x-pixel** [comment]
Thank you for the clarification, I understand what I have overlooked here.
So the issue can be closed.
