### ISSUE TITLE
ESP32-2432S022C Support

### ISSUE THREAD

**Issue by cycada** [suchmememanyskill/CYD-Klipper#42]
Would it be possible for you to add support for the ESP32-2432S022C screen?

**Comment by suchmememanyskill** [comment]
@cycada https://github.com/suchmememanyskill/CYD-Klipper/actions/runs/7875543399

Can you try this build? Grab the merged-firmware .bin from the github actions artifact firmware zip, install esptool and run `esptool write_flash 0x0 merged-firmware.bin`

**Comment by cycada** [comment]
The file seemed to flash OK, but I just end up with blank screen with the backlight turned off.
I think I'll get the 3.8" display anyway, 2.2 is a bit small for this.
Thanks.
