### ISSUE TITLE
Use websockets instead of polling the http API every couple of seconds.

### ISSUE THREAD

**Issue by degraafm76** [suchmememanyskill/CYD-Klipper#50]
Mainsail is using websockets to access the moonraker API. Is it possible to implement websockets in CYD-Klipper? This would make updates to the screen almost instant.

**Comment by suchmememanyskill** [comment]
That's how i started out the project. One small issue, websocks seem to be fundementally broken on esp32. I constantly got socket disconnects.

So i just chose to fetch data every second instead
