### ISSUE TITLE
Layer progress not shown

### ISSUE THREAD

**Issue by szafranski** [suchmememanyskill/CYD-Klipper#59]
![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/23621888/9fa50cae-c82b-41f6-98dc-e6535bd30892)

As shown above

**Comment by suchmememanyskill** [comment]
This is an issue with your configuration

https://moonraker.readthedocs.io/en/latest/printer_objects/#print_stats see 'info'

**Comment by szafranski** [comment]
Thank you, but looks like virtual_sdcard has to be addod so it would be active. I have this feature so I am not sure what I am doing wrong.

**Comment by suchmememanyskill** [comment]
I don't know what you are looking at, but it's not what i sent you

![Screenshot_20240307-223020_Pixel Launcher.png](https://github.com/suchmememanyskill/CYD-Klipper/assets/38142618/34024f4c-66d5-4a0d-9ec0-0b33abeb2e45)

**Comment by szafranski** [comment]
Oh, my bad. Thank you so much for your time!
