### ISSUE TITLE
Layer is always 0/0

### ISSUE THREAD

**Issue by aam335** [suchmememanyskill/CYD-Klipper#64]
![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/32163139/d0ff122c-e645-43e7-8691-d906ad55a319)

**Comment by themacboy** [comment]
ummm probably you need to setup pause in next laye and pause at layer function. Have you do it?

**Comment by aam335** [comment]
So strange. The layers are successfully displayed in the fluidd dashboard.

> ummm probably you need to setup pause in next laye and pause at layer function. Have you do it?
Added, thanks
