### ISSUE TITLE
[Enhancement/Feature Request] Request for emergency stop button 

### ISSUE THREAD

**Issue by aam335** [suchmememanyskill/CYD-Klipper#65]
It would be nice to have an emergency stop button on the left menu. Very useful for various kinematics and limit switch tune-ups and tests

**Comment by suchmememanyskill** [comment]
I think this would be a bad idea as it can easily accidentally be pressed.
Besides this, another button will be added soon to the left side menu (a printer button to allow multi printer operations). I think it'll get too cluttered including such an emergency  stop button.

If you want one, probably best to add one as a macro and call M999 (iirc)
