### ISSUE TITLE
Web install failure ...

### ISSUE THREAD

**Issue by themacboy** [suchmememanyskill/CYD-Klipper#67]
Good morning,

when trying to update from web service I get this error:

![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/8063711/5d1ccf58-2c75-44ba-8b8a-8577224d73fa)

There is no problem for me, I will compile on platformio, but I think you must know ;)

**Comment by KulibinBoris** [comment]
Good afternoon.
I have the same problem, I can’t install the firmware via the web interface for the ESP32-8048S043, on 2.8" everything works fine, but the size is too small for me, I can’t see well. Could you help me?

**Comment by suchmememanyskill** [comment]
@KulibinBoris see https://github.com/suchmememanyskill/CYD-Klipper/blob/dev/Manual_Install.md#building--flashing-via-platformio for how to install via platformio. Might be worthwhile to install via platformio anyway as you can tweak the size of buttons and text in cyd klipper

**Comment by dronecz** [comment]
@suchmememanyskill I can not find proper JSON files (I guess that they are automaticaly generated) to make PR, but you have to change `"chipFamily": "ESP32"` to `"chipFamily": "ESP32-S3"` and flasher should work.

**Comment by suchmememanyskill** [comment]
@dronecz thank you for the suggestion/fix.

The board definitions are present in /CYD-Klipper/boards

**Comment by dronecz** [comment]
I mean in web definition. File with this content:

 `{"name": "to esp32-8048S043C-SD", "funding_url": "https://ko-fi.com/suchmememanyskill", "new_install_prompt_erase": true, "builds": [{"chipFamily": "ESP32", "parts": [{"path": "out/esp32-8048S043C-SD/bootloader.bin", "offset": 4096}, {"path": "out/esp32-8048S043C-SD/partitions.bin", "offset": 32768}, {"path": "out/esp32-8048S043C-SD/boot_app0.bin", "offset": 57344}, {"path": "out/esp32-8048S043C-SD/firmware.bin", "offset": 65536}]}]}`

**Comment by suchmememanyskill** [comment]
@dronecz Can you test if this works now

**Comment by dronecz** [comment]
> @dronecz Can you test if this works now

Yes, I can confirm that flashing works on my board with ESP32-S3 module.
