### ISSUE TITLE
"Printer is not ready" Error

### ISSUE THREAD

**Issue by crazy-hair** [suchmememanyskill/CYD-Klipper#71]
On the latest firmware (1.5) I'm getting an error screen like this every 15s-1m:

![PXL_20240322_001051682](https://github.com/suchmememanyskill/CYD-Klipper/assets/9155262/4e307238-3996-4b71-8839-33f5c48c332d)

It stays on screen for about 5 seconds, but when it goes away it knocks you back out into the main screen, interrupting whatever I was currently doing.

**Comment by suchmememanyskill** [comment]
Possibly caused by https://github.com/suchmememanyskill/CYD-Klipper/blob/master/CYD-Klipper/src/core/data_setup.cpp#L224?

Seems like a moonraker fault, but i'll remove that line and send you a build when i have the time to do so

**Comment by suchmememanyskill** [comment]
Can you try the following build? https://github.com/suchmememanyskill/CYD-Klipper/actions/runs/8396463313

**Comment by crazy-hair** [comment]
From about 5 minutes of testing, with the older firmware running on another screen, I got 3 popups on the old firmware and none on the new one. So far, so good.
