### ISSUE TITLE
All macros are missing

### ISSUE THREAD

**Issue by systemerror-codenotfound** [suchmememanyskill/CYD-Klipper#77]
So, i have my screen connected to Klipper and all works fine, but i can't see any of my Macros on the screen, like they don't exist

This is a screenshot from moonraker

![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/24920928/0471db3c-3687-4d28-8caf-716a2d1180a2)

![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/24920928/d0cac400-330b-4fc7-ae9d-d6381ed44da1)

![image](https://github.com/suchmememanyskill/CYD-Klipper/assets/24920928/395c411a-f0bc-4325-a8c5-9434c3e313bd)

The only "macro" that appear is a switch that is configured as "Power Devices"

**Comment by systemerror-codenotfound** [comment]
Fixed by adding description: CYD_SCREEN_MACRO on each macro

This should be on the readme description

**Comment by suchmememanyskill** [comment]
Fixed in f5f970a
