### ISSUE TITLE
Files list available when printing

### ISSUE THREAD

**Issue by szafranski** [suchmememanyskill/CYD-Klipper#80]
Would it be possible to make files list accessible during the print? Not to start the new print (of course),
just to view what files are present in the memory.

**Comment by suchmememanyskill** [comment]
Why would you want to see what files you can print without actually being able to print them?

While yes, you can show the file list while printing quite easily, i really do not see the point. Especially when screen space is at a premium and showing one more button will probably make the ui more cluttered than it needs to be

**Comment by szafranski** [comment]
To check if some file was already sliced and sent. I mean there is plenty of space near the pause button. On 29 Mar 2024, at 19:11, Sims ***@***.***> wrote:﻿
Why would you want to see what files you can print without actually being able to print them?
While yes, you can show the file list while printing quite easily, i really do not see the point. Especially when screen space is at a premium and showing one more button will probably make the ui more cluttered than it needs to be

**Comment by suchmememanyskill** [comment]
Implemented in latest release
