### ISSUE TITLE
Screen not connected to the Wi-Fi after wakeup

### ISSUE THREAD

**Issue by szafranski** [suchmememanyskill/CYD-Klipper#82]
Sometimes my screen is not being connected to the Wi-Fi after being in the sleep state. I have to reboot it and then it connects in few seconds correctly.

**Comment by suchmememanyskill** [comment]
What do you mean with the screen not being connected to WIFI?

Can you get some logs for me to analyse?

Also, if the CYD detects that it loses its connection, it will reboot. I assume you have not seen this behaviour happen?

**Comment by szafranski** [comment]
I believe it was being stuck on „connecting to WiFi” screen, right after being woke up. No, it was just stuck there. I will try to catch this and then report.On 29 Mar 2024, at 19:15, Sims ***@***.***> wrote:﻿
What do you mean with the screen not being connected to WIFI?
Can you get some logs for me to analyse?
Also, if the CYD detects that it loses its connection, it will reboot. I assume you have not seen this behaviour happen?

**Comment by suchmememanyskill** [comment]
Issue seems to be stale, closing
