### ISSUE TITLE
Ability to make folders in macros menu

### ISSUE THREAD

**Issue by szafranski** [suchmememanyskill/CYD-Klipper#89]
Hi! It's me again ;) I would like to request the ability to make folders in macros menu. I can explain more if needed. Thank you for the awesome work!

**Comment by suchmememanyskill** [comment]
Why do you need so many macros, out of curiosity?

Also this would be very annoying to implement, and would require some non standard data (like some foldername in a macro name). Not a huge fan of implementing this

**Comment by szafranski** [comment]
Actually you maybe right. I like to have all my macros at hand, when near
the printer but it is nor required actually. What about ordering them with
alphabetical order at least then?

Pawel

pon., 15 kwi 2024 o 21:13 Sims ***@***.***> napisał(a):

**Comment by suchmememanyskill** [comment]
Do they not show up in the same order as they are placed in the printer.cfg file?

**Comment by szafranski** [comment]
Oh, yes, they are in the same order as in the config. Could there be the option to sort them alphabetically in the menu or sth then? :)

**Comment by suchmememanyskill** [comment]
Implemented in latest release
