### ISSUE TITLE
ESP32-4827S043C Manual flash 

### ISSUE THREAD

**Issue by fanatykCZ516** [suchmememanyskill/CYD-Klipper#97]
ESP32-4827S043C not supported. I use manual flashing, but get black screan. 
![Знімок екрана 2024-05-03 200522](https://github.com/suchmememanyskill/CYD-Klipper/assets/153854836/3f50479f-4f65-4623-93d6-f889e70b2281)

**Comment by suchmememanyskill** [comment]
@fanatykCZ516 what happens if you run it via platformio?

**Comment by fanatykCZ516** [comment]
> @fanatykCZ516 what happens if you run it via platformio?

All fine, board works) TNX so match

**Comment by suchmememanyskill** [comment]
(Closing as this issue is a dupe of #67 )
